version: '3'

services:
  mopidy:
    build:
      context: .
      args:
        - ARCH
    container_name: mopidy
    image: audiostation/mopidy:${ARCH}
    ports:
      - "6600:6600"
      - "6680:6680"
      - "5555:5555"
