services:
  - docker

jobs: 
  include:
    - stage: build
      env:
        - compose_file: container/mopidy/docker-compose.yml
    - env:
        - compose_file: container/snapcast/docker-compose.yml
    - env:
        - compose_file: container/spotify/docker-compose.yml
    - env:
        - compose_file: container/upmpdcli/docker-compose.yml
    - stage: deploy
      env:
        - compose_file: docker-compose.yml


script:
  - docker-compose -f $compose_file build
  - docker-compose -f $compose_file up -d
  - docker-compose -f $compose_file down

stages:
  - build
  - deploy
