services:
  - docker

jobs: 
  include:
    - stage: build
      env:
        - container: mopidy
    - env:
        - container: snapcast
    - env:
        - container: spotify
    - env:
        - container: upmpdcli
    - stage: compose
      script:
        - docker-compose build
        - docker-compose up -d
        - docker-compose down

script:
  - docker-compose -f container/$container/docker-compose.yml build
  - docker-compose -f container/$container/docker-compose.yml up -d
  - docker-compose -f container/$container/docker-compose.yml down
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push audiostation/$container:latest
