services:
  - docker

before_install:
  - sudo apt-get install qemu-system-arm


jobs: 
  include:
    # AMD64 builds
    - stage: build
      env:
        - CONTAINER: mopidy
        - BUILDARCH: amd64
        - FROMIMAGE: alpine:3.8
        - DOCKERFILE: container/mopidy/docker-compose.yml
    - env:
        - CONTAINER: snapcast
        - BUILDARCH: amd64
        - FROMIMAGE: alpine:3.8
        - DOCKERFILE: container/snapcast/docker-compose.yml
    - env:
        - CONTAINER: spotify
        - BUILDARCH: amd64
        - FROMIMAGE: debian:jessie-slim
        - DOCKERFILE: container/spotify/docker-compose.yml
    - env:
        - CONTAINER: upmpdcli
        - BUILDARCH: amd64
        - FROMIMAGE: alpine:3.8
        - DOCKERFILE: container/upmpdcli/docker-compose.yml

    - env:
        - CONTAINER: mopidy
        - BUILDARCH: armv6
        - FROMIMAGE: multiarch/alpine:armhf-v3.8
        - DOCKERFILE: container/mopidy/docker-compose.yml
    - env:
        - CONTAINER: snapcast
        - BUILDARCH: armv6
        - FROMIMAGE: multiarch/alpine:armhf-v3.8
        - DOCKERFILE: container/snapcast/docker-compose.yml
    - env:
        - CONTAINER: spotify
        - BUILDARCH: armv6
        - FROMIMAGE: multiarch/ubuntu-core:armhf-bionic
        - DOCKERFILE: container/spotify/docker-compose.yml
    - env:
        - CONTAINER: upmpdcli
        - BUILDARCH: armv6
        - FROMIMAGE: multiarch/debian-debootstrap:armhf-stretch-slim
        - DOCKERFILE: container/upmpdcli/docker-composeRPI.yml
    - stage: compose
      script:
        - docker-compose build
        - docker-compose up -d
        - docker-compose down

script:
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  - docker-compose -f $DOCKERFILE build --build-arg FROMIMAGE=$FROMIMAGE --build-arg BUILDARCH=$BUILDARCH $CONTAINER
  - docker-compose -f $DOCKERFILE up -d
  - docker-compose -f $DOCKERFILE down
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push audiostation/$CONTAINER:${BUILDARCH}
