services:
  - docker

before_install:
  - sudo apt-get install qemu-system-arm


jobs: 
  include:
    # AMD64 builds
    - stage: build
      env:
        - container: mopidy
        - arch: amd64
        - fromimage: alpine:3.8
        - dockerfile: container/mopidy/docker-compose.yml
    - env:
        - container: snapcast
        - arch: amd64
        - fromimage: alpine:3.8
        - dockerfile: container/snapcast/docker-compose.yml
    - env:
        - container: spotify
        - arch: amd64
        - fromimage: debian:jessie-slim
        - dockerfile: container/spotify/docker-compose.yml
    - env:
        - container: upmpdcli
        - arch: amd64
        - fromimage: alpine:3.8
        - dockerfile: container/upmpdcli/docker-compose.yml

    - env:
        - container: mopidy
        - arch: armv6
        - fromimage: multiarch/alpine:armhf-v3.8
        - dockerfile: container/mopidy/docker-compose.yml
      script:
        - docker run --rm --privileged multiarch/qemu-user-static:register --reset
        - docker-compose -f $dockerfile build
        - docker-compose -f $dockerfile up -d
        - docker-compose -f $dockerfile down
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push audiostation/$container:${arch}
    - env:
        - container: snapcast
        - arch: armv6
        - fromimage: multiarch/alpine:armhf-v3.8
        - dockerfile: container/snapcast/docker-compose.yml
      script:
        - docker run --rm --privileged multiarch/qemu-user-static:register --reset
        - docker-compose -f $dockerfile build
        - docker-compose -f $dockerfile up -d
        - docker-compose -f $dockerfile down
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push audiostation/$container:${arch}
    - env:
        - container: spotify
        - arch: armv6
        - fromimage: multiarch/ubuntu-core:armhf-bionic
        - dockerfile: container/spotify/docker-compose.yml
      script:
        - docker run --rm --privileged multiarch/qemu-user-static:register --reset
        - docker-compose -f $dockerfile build
        - docker-compose -f $dockerfile up -d
        - docker-compose -f $dockerfile down
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push audiostation/$container:${arch}
    - env:
        - container: upmpdcli
        - arch: armv6
        - fromimage: multiarch/alpine:armhf-v3.8
        - dockerfile: container/upmpdcli/docker-compose.yml
      script:
        - docker run --rm --privileged multiarch/qemu-user-static:register --reset
        - docker-compose -f $dockerfile build
        - docker-compose -f $dockerfile up -d
        - docker-compose -f $dockerfile down
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push audiostation/$container:${arch}
    - stage: compose
      script:
        - docker-compose build
        - docker-compose up -d
        - docker-compose down

script:
  - docker-compose -f $dockerfile build
  - docker-compose -f $dockerfile up -d
  - docker-compose -f $dockerfile down
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push audiostation/$container:${arch}
