version: '3'
services:
  data:
    build:
      context: .
    volumes:
      - soundshare:/tmp/sharesound

  mopidy:
    image: deisi/mopidy
    ports:
      - "6600:6600"
      - "6680:6680"
    depends_on:
      - snapserver
      - data
    volumes:
      - ./mopidy-master.conf:/var/lib/mopidy/.config/mopidy/mopidy.conf:ro
      - soundshare:/tmp/sharesound
    restart: unless-stopped

  snapserver:
    image: deisi/snapcast-server
    depends_on:
      - data
    volumes:
      - soundshare:/tmp/sharesound
    command: "-s pipe:///tmp/sharesound/snapfifo?name=Radio"
    ports:
      - "1704:1704"
      - "1705:1705"
    restart: unless-stopped

  #snapclient:
  #  image: deisi/snapcast-client
  #  links:
  #   - snapserver:snapserverhost
  #  depends_on:
  #    - snapserver
  #  devices:
  #   - "/dev/snd/:/dev/snd/"
  #  command: "-h snapserver"
  #  restart: unless-stopped

  upmpdcli:
    image: deisi/upmpdcli
    depends_on:
      - mopidy
    command: "-h mopidy -p 6600 -f mopidy"
    restart: unless-stopped

volumes:
  soundshare:
