version: '3'

volumes:
  # A volume to store mopify data in a persitent way.
  mopidy_data:

services:
  mopidy:
    image: audiostation/mopidy:1.2
    ports:
      - "6600:6600"
      - "6680:6680"
      - "5555:5555"
    depends_on:
      - snapserver
    volumes:
      # The volume with the sharesound fifo for snapcast to work
      - /tmp/sharesound:/tmp/sharesound
      # A config of mopidy that pipes audio into the snapfifo
      - ./mopidy-master.conf:/etc/mopidy/mopidy.conf:ro
      - mopidy_data:/var/lib/mopidy
    restart: unless-stopped

  snapserver:
    image: audiostation/snapcast:1.1
    volumes:
      # The volume with the sharesound fifo for snapcast to work
      - /tmp/sharesound:/tmp/sharesound
    command: "snapserver -s pipe:///tmp/sharesound/snapfifo?name=Radio"
    # host mode is needed for snapserver advertisement
    network_mode: "host"
    # Instead of hostmode you can allow the specific snapcast ports.
    # This is more secure, but has the drawback, that advertisement
    # doesn't work.
    #ports:
    #  - "1704:1704"
    #  - "1705:1705"
    restart: unless-stopped

  spotify:
    image: audiostation/spotify:1.2
    # host mode is needed for Spotifyd advertisement
    network_mode: "host"
    volumes:
      # The volume with the sharesound fifo for snapcast to work
      - /tmp/sharesound:/tmp/sharesound
    restart: unless-stopped

  upmpdcli:
    image: audiostation/upmpdcli:1.0
    command: "-h mopidy"
    # Host mode needed for advertisement
    netowk_mode: "host"
    #ports:
    #  - "1900/udp:1900/udp"
    #  - 49152:49152


  # Turn this on if you have no other snapcast client on the server
  #snapclient:
  #  image: audiostation/snapcast:v1.0
  #  links:
  #   - snapserver:snapserverhost
  #  depends_on:
  #    - snapserver
  #  devices:
  #   - "/dev/snd/:/dev/snd/"
  #  command: "snapclient -h snapserver"
  #  restart: unless-stopped
