version: '3'

services:
  snapcast:
    build:
      context: .
      args:
        - FROMIMAGE
    image: "audiostation/snapcast:${SARCH}"
    # This command is here for test purpose
    command: "snapclient -h snapserver"
