version: '3'

services:
  spotify:
    build:
      context: .
      args:
        - ARCH
        - FROMIMAGE
    container_name: spotify
    network_mode: "host"
    volumes:
      - /tmp/sharesound:/tmp/sharesound
